Sorting fast
TristanPouliquen/selection-poste-enm pull request #45
Opened 2023-03-05 14:43 UTC by VladimirChantitch

Fast sorting algorythm

--> Each kind of criterion has its own method whihch is called in some sort of reponsability chain. 

--> I Changed number criterion value for string to make it work with the DB// This still has to be changed in the front.

2023-03-05 17:19 UTC, TristanPouliquen requested changes
Top comme code ! J'ai appris quelques syntaxes de Rust au passage 😅

2023-03-05 17:19 UTC, TristanPouliquen commented on .gitignore
> +yarn.lock
yarn.lock on le laisse, c'est ce qui indique quelle version des dépendances front est utlisée :) 

package-lock.json c'est en utilisant NPM, Yarn2 est préféré.

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/main.rs
> +fn get_sortedPositions(app_handle: tauri::AppHandle, sortDataInput : SortDataInput) -> bool {
je l'appellerais plutôt `sort_positions` parce que c'est ce qu'elle fait plutôt que récupérer les positions ordonnées.

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/main.rs
> +    return document_delete(db_path, document);
en Rust, le return est implicite sur la dernière ligne sans ; à la fin.

Tu peux revert cette ligne et appliquer le même changement sur ta commande du dessus

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +use super::tribunal;
je ne connais pas, ça fait quoi `super::` ?

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +    let positions = position_list(path.to_string());
besoin du .toString() ?

De mémoire, dans `update_ranking` je ne l'utilisais pas.

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +                for (idx) in &array{
tu peux run `cargo fmt` et `cargo clippy` depuis le dossier `src-tauri`, ça corrigera quelques erreurs de code style comme cet espace oublié.

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +                for (idx) in &array{
Le nom de variable `array` n'est vraiment pas explicite.

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +        indexor += 1;
ça sert à quoi ça ?

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +#[derive(Serialize, Deserialize)]
tu as juste besoin du Deserialize là non ? vu qu'on ne l'expose pas de Rust vers le JS

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +
ça serait un peu plus léger de faire un update juste du ranking pour chaque position non ? 

VU qu'il n'y a pas de contraintes d'unicité, tu traverses ton Vec et tu sets le ranking en fonction de l'index. 

`position_update_ranking` update à chaque fois plusieurs rows

2023-03-05 17:19 UTC, TristanPouliquen commented on src-tauri/src/models/tribunal.rs
> +        Err(diesel::NotFound) => return false,
pas très utile de séparer les deux si tu retournes la même chose.

2023-03-05 19:36 UTC, VladimirChantitch commented on .gitignore
> +yarn.lock
Ah ok mdr

2023-03-05 19:38 UTC, VladimirChantitch commented on src-tauri/src/models/position.rs
> +use super::tribunal;
ça permet d'accèder à tous ce que contient le module parent

2023-03-05 19:39 UTC, VladimirChantitch commented on src-tauri/src/main.rs
> +    return document_delete(db_path, document);
Trop stylé

2023-03-05 19:39 UTC, VladimirChantitch commented on src-tauri/src/main.rs
> +fn get_sortedPositions(app_handle: tauri::AppHandle, sortDataInput : SortDataInput) -> bool {
Oui ta raison je suis assez d'accord avec toi :D

2023-03-05 19:40 UTC, VladimirChantitch commented on src-tauri/src/models/position.rs
> +    let positions = position_list(path.to_string());
Pas besoins en fait c'est moi qui me suis empatouillé avec les ref, les pointer, les mut XD

2023-03-05 19:41 UTC, VladimirChantitch commented on src-tauri/src/models/position.rs
> +                for (idx) in &array{
ho stylé ça

2023-03-05 19:41 UTC, VladimirChantitch commented on src-tauri/src/models/position.rs
> +                for (idx) in &array{
on est d'accord c'est claqué au sol je te change ça demain :D

2023-03-05 19:43 UTC, VladimirChantitch commented on src-tauri/src/models/position.rs
> +        indexor += 1;
a la ranquer dans l'ordre non ? 
genre j'ai ma liste pondérée je la range puis pour chaque éléments je met le nouveau ranking et après j'update le ranking 

(attend :: le ranking dans position ça n'a aucun lien avec le sorting ?)

2023-03-05 19:44 UTC, VladimirChantitch commented on src-tauri/src/models/position.rs
> +#[derive(Serialize, Deserialize)]
C'est totatlment vrai,

2023-03-05 19:46 UTC, VladimirChantitch commented on src-tauri/src/models/position.rs
> +
attend yah des for loop "classic" en rust ? Lets go

2023-03-05 19:47 UTC, VladimirChantitch commented on src-tauri/src/models/tribunal.rs
> +        Err(diesel::NotFound) => return false,
Bah là c'est qu'il ne voulais pas compilé si je ne faisais pas un handle de tous les case du Match 
Du coup Rust ne m'a pas trop laissé le choix, mais en vrai je ferais mieux de trhown un prinln en plus du return

2023-03-06 17:02 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +        indexor += 1;
ah pardon j'avais mal lu !

2023-03-06 17:03 UTC, TristanPouliquen commented on src-tauri/src/models/position.rs
> +
je pense

2023-03-06 17:03 UTC, TristanPouliquen commented on src-tauri/src/models/tribunal.rs
> +        Err(diesel::NotFound) => return false,
OK !

2023-03-06 17:04 UTC, TristanPouliquen commented
@VladimirChantitch tu as encore le linter de Rust qui n'est pas content visiblement :)

2023-03-06 17:06 UTC, TristanPouliquen commented on .gitignore
> +yarn.lock
ne committe pas le fichier package-lock.json pour autant, y'a déjà le yarn.lock qui fait le même taf :)

2023-03-12 13:29 UTC, merged